name: ldm_db
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.15
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - curl=8.12.1
  - cython=0.29.36
  - expat=2.7.1
  - ffmpeg=4.3
  - freetype=2.13.3
  - gettext=0.21.0
  - git=2.45.2
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=73.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.7
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - perl=5.38.2
  - pillow=10.4.0
  - pip=20.3.3
  - pysocks=1.7.1
  - python=3.8.20
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tk=8.6.14
  - torchtriton=2.1.0
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - argcomplete==3.6.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - boto==2.49.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - clarabel==0.9.0
      - click==8.1.8
      - clip==1.0
      - cloudpickle==3.1.1
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==43.0.3
      - cvxpy==1.5.2
      - cycler==0.12.1
      - datasets==2.16.1
      - diffusers==0.33.0
      - dill==0.3.7
      - ecos==2.0.14
      - einops==0.8.1
      - fasteners==0.20
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2023.10.0
      - ftfy==6.2.3
      - future==1.0.0
      - gcs-oauth2-boto-plugin==3.2
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-reauth==0.1.1
      - grpcio==1.70.0
      - gsutil==5.34
      - gym==0.26.2
      - gym-notices==0.1.0
      - higher==0.2.1
      - httplib2==0.20.4
      - huggingface-hub==0.30.2
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.8
      - learn2learn==0.2.0
      - lightning-utilities==0.11.9
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - monotonic==1.6
      - multidict==6.1.0
      - multiprocess==0.70.15
      - natsort==8.4.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.32.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - osqp==1.0.4
      - packaging==25.0
      - pandas==2.0.3
      - propcache==0.2.0
      - protobuf==3.20.1
      - psutil==7.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydeprecate==0.3.2
      - pyopenssl==24.2.1
      - pyparsing==3.1.4
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytorch-lightning==1.6.5
      - pytz==2025.2
      - pyu2f==0.1.5
      - qpth==0.0.18
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - retry-decorator==1.1.1
      - rsa==4.7.2
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - scs==3.2.7.post2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - test-tube==0.7.5
      - timm==1.0.15
      - tokenizers==0.15.2
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchmetrics==1.5.2
      - torchvision==0.16.2+cu118
      - tqdm==4.67.1
      - transformers==4.38.0
      - triton==2.1.0
      - tzdata==2025.2
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - xformers==0.0.23.post1+cu118
      - xxhash==3.5.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /data/New_User/Hby/.conda/envs/ldm_db
